{{ if .Values.apps }}{{ if .Values.apps.bahmni_mart }} {{ if .Values.apps.bahmni_mart.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-mart
spec:
  selector:
    matchLabels:
      app: bahmni-mart
  template:
    metadata:
      labels:
        app: bahmni-mart
    spec:
      volumes:
        - name: distro
          persistentVolumeClaim:
            claimName: distro-pvc
        - name: mart-props-vol
          configMap:
            name: mart-props
        - name: mart-db-init
          configMap:
            name: mart-db-scripts
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
      initContainers:
        - name: init-db
          image: "{{ .Values.docker_registry }}/{{ .Values.apps.bahmni_mart.initImage }}" 
          volumeMounts:
            - name: mart-db-init
              mountPath: "/mnt/"
          command: ['sh', '-c', "bash /mnt/create_analytics_db.sh"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_DB
            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_PASSWORD
            - name: ANALYTICS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_HOST
            - name: ANALYTICS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_NAME
            - name: ANALYTICS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_USER
            - name: ANALYTICS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_PASSWORD
      containers:
      - name: bahmni-mart
        image: "{{ .Values.docker_registry }}/{{ .Values.apps.bahmni_mart.image }}" 
        resources:
            requests:
              memory: "{{  .Values.apps.bahmni_mart.resources.requests.memory }}"
              cpu: "{{ .Values.apps.bahmni_mart.resources.requests.cpu }}"
        volumeMounts:
            - name: distro
              mountPath: "/var/www"
              subPath: "bahmni_config/"
            - name: mart-props-vol
              mountPath: "/opt/bahmni-mart/conf"
            - name: data
              subPath: "openmrs/bahmni"
              mountPath: "/home/bahmni/"
        env:
            - name: OPENMRS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_HOST
            - name: OPENMRS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_NAME
            - name: OPENMRS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_USER
            - name: OPENMRS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: openmrs-configs
                  key: OPENMRS_DB_PASSWORD
            - name: ANALYTICS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_HOST
            - name: ANALYTICS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_NAME
            - name: ANALYTICS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_USER
            - name: ANALYTICS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: ANALYTICS_DB_PASSWORD
            - name: CRON_TIME
              valueFrom:
                configMapKeyRef:
                  name: mart-config
                  key: CRON_TIME
{{ end }}{{ end }}{{ end }}