{{ if .Values.apps }}{{ if .Values.apps.bahmni_filestore }} {{ if .Values.apps.bahmni_filestore.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-filestore
spec:
  selector:
    matchLabels:
      app: bahmni-filestore
  template:
    metadata:
      labels:
        app: bahmni-filestore
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
      containers:
      - name: bahmni-filestore
        image: "{{ .Values.docker_registry }}/{{ .Values.apps.bahmni_filestore.image }}" 
        resources:
            requests:
              memory: "{{  .Values.apps.bahmni_filestore.resources.requests.memory }}"
              cpu: "{{ .Values.apps.bahmni_filestore.resources.requests.cpu }}"
        volumeMounts:
            - name: data
              subPath: "openmrs/bahmni"
              mountPath: "/usr/share/nginx/html/"
        ports:
        - containerPort: 80
{{ end }}{{ end }}{{ end }}