{{ if .Values.apps }}{{ if .Values.apps.bahmni_config }} {{ if .Values.apps.bahmni_config.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bahmni-config
spec:
  selector:
    matchLabels:
      app: bahmni-config
  template:
    metadata:
      labels:
        app: bahmni-config
    spec:
      volumes:
        - name: distro
          persistentVolumeClaim:
            claimName: distro-pvc
      containers:
      - name: bahmni-config
        image: "{{ .Values.docker_registry }}/{{ .Values.apps.bahmni_config.image }}" 
        resources:
            requests:
              memory: "{{  .Values.apps.bahmni_config.resources.requests.memory }}"
              cpu: "{{ .Values.apps.bahmni_config.resources.requests.cpu }}"
        volumeMounts:
            - name: distro
              subPath: "bahmni_config/"
              mountPath: "/usr/share/nginx/html"
        ports:
        - containerPort: 80
{{ end }}{{ end }}{{ end }}