{{ if .Values.apps }}{{ if .Values.apps.openelis }} {{ if .Values.apps.openelis.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openelis
spec:
  selector:
    matchLabels:
      app: openelis
  template:
    metadata:
      labels:
        app: openelis
    spec:
      volumes:
        - name: openelis-props
          configMap:
            name: openelis-config
        - name: openelis-db-init
          configMap:
            name: openelis-db-init
        - name: log
          emptyDir: {}
      initContainers:
        - name: init-db
          image: "{{ .Values.docker_registry }}/{{ .Values.apps.openelis.initImage }}"
          volumeMounts:
            - name: openelis-db-init
              mountPath: "/mnt/"
          command: ['sh', '-c', "sh /mnt/create_openelis_db.sh"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_DB
            - name: POSTGRES_USER 
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configs
                  key: POSTGRES_PASSWORD
            - name: OPENELIS_DB_NAME 
              valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_NAME
            - name: OPENELIS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_USER
            - name: OPENELIS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_PASSWORD
            - name: OPENELIS_DB_HOST
              valueFrom:
                  configMapKeyRef:
                    name: openelis-db-config
                    key: OPENELIS_DB_HOST
      priorityClassName: high-priority
      containers:
      - name: logging
        image: "{{ .Values.docker_registry }}/{{ .Values.apps.openelis.loggingImage }}"
        args: [/bin/sh, -c, 'while ! tail -f /usr/local/tomcat/logs/openelis.log ; do sleep 1 ; done']
        volumeMounts:
          - name: log
            mountPath: /usr/local/tomcat/logs
      - name: openelis
        image: "{{ .Values.docker_registry }}/{{ .Values.apps.openelis.image }}"
        resources:
            requests:
              memory: "{{  .Values.apps.openelis.resources.requests.memory }}"
              cpu: "{{ .Values.apps.openelis.resources.requests.cpu }}"
        volumeMounts:
            - name: openelis-props
              mountPath: "/etc/properties/"
            - name: log
              mountPath: /usr/local/tomcat/logs
        ports:
        - name: http
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /openelis
            port: http
          failureThreshold: 50
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /openelis
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /openelis
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: OPENELIS_DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_HOST
          - name: OPENMRS_HOST
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_HOST
          - name: OPENMRS_USER
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_USER
          - name: OPENMRS_DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_HOST
          - name: OPENMRS_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_PASSWORD
          - name: OPENMRS_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_DB_USER
          - name: OPENMRS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: openmrs-configs
                key: OPENMRS_PASSWORD
          - name: OPENELIS_DB_USER
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_USER
          - name: OPENELIS_DB_PASSWORD
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_PASSWORD
          - name: OPENELIS_DB_NAME
            valueFrom:
                configMapKeyRef:
                  name: openelis-db-config
                  key: OPENELIS_DB_NAME
          - name: ATOMFEED_PROPERTIES_FILE_PATH
            value: /etc/properties/atomfeed.properties
          - name: HIBERNATE_PROPERTIES_FILE_PATH
            value: /etc/properties/hibernate.properties
{{ end }}{{ end }}{{ end }}





