{{ if .Values.apps }}{{ if .Values.apps.implementer_interface }} {{ if .Values.apps.implementer_interface.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: implementer-interface
spec:
  selector:
    matchLabels:
      app: implementer-interface
  template:
    metadata:
      labels:
        app: implementer-interface
    spec:
      volumes:
        - name: distro
          persistentVolumeClaim:
            claimName: distro-pvc
        - name: httpd-config
      containers:
      - name: implementer-interface
        image: "{{ .Values.docker_registry }}/{{ .Values.apps.implementer_interface.image }}"
        resources:
            requests:
              memory: "{{  .Values.apps.implementer_interface.resources.requests.memory }}"
              cpu: "{{ .Values.apps.implementer_interface.resources.requests.cpu }}"
        ports:
        - containerPort: 8902
{{ end }}{{ end }}{{ end }}