{{ if .Values.apps }}{{ if .Values.apps.mysql }} {{ if .Values.apps.mysql.enabled }} 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  serviceName: {{ .Release.Name }}-mysql-headless
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  {{- if ne .Values.isAppliance true }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-mysql-database
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
    {{ if .Values.isAppliance }}
      volumes:
        - name: {{ .Release.Name }}-mysql-database
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
     {{ end }}
      containers:
        - name: {{ .Release.Name }}-mysql
          image: {{ .Values.apps.mysql.image }}
          ports:
            - containerPort: 3306
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            exec:
              command:
                - "sh"
                - "-c"
                - 'mysql -uroot -p${MYSQL_ROOT_PASSWORD} -h localhost -e "SELECT 1"'
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            exec:
              command:
                - "sh"
                - "-c"
                - 'mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD} ping'
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: {{ .Release.Name }}-mysql-database
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-configs
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-mysql-configs
                  key: MYSQL_ROOT_USER
    {{ if .Values.selectDbHost }}
     {{- with .Values.apps.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{ end }}{{ end }}{{ end }}
