{{ if .Values.apps }}{{ if .Values.apps.appointments }} {{ if .Values.apps.appointments.enabled }} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments
spec:
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: bahmni-config
        image:  "{{ .Values.docker_registry }}/{{ .Values.apps.appointments.image }}"
        resources:
            requests:
              memory: "{{  .Values.apps.appointments.resources.requests.memory }}"
              cpu: "{{ .Values.apps.appointments.resources.requests.cpu }}"
            
        ports:
        - containerPort: 8903
{{ end }}{{ end }}{{ end }}